### ISSUE TITLE
jsonpointer: flatten/unflatten does not preserve arrays with more than 10 elements

### ISSUE THREAD

**Issue by NiN9876** [danielaparker/jsoncons#644]
**Describe the bug**

We encountered a problem with the jsonpointer extension when used with sorted objects  json/wjson. When an array is flattened and then unflattened it is preserved only if its size is 10 or less. 

**Include a small, self-contained example if possible**

```
​#include "jsoncons/json.hpp"
#include "jsoncons_ext/jmespath/jmespath.hpp"
#include <jsoncons_ext/jsonpointer/jsonpointer.hpp>
#include <jsoncons_ext/jsonpointer/jsonpointer_error.hpp>

#include <iostream>
#include <string>

inline std::string PrettyPrint(const jsoncons::json &data) {
  std::ostringstream oss;
  oss << jsoncons::pretty_print(
      data, jsoncons::json_options{}.indent_size(2).spaces_around_comma(
                jsoncons::spaces_option::no_spaces));
  return oss.str();
}

int main() 
{

    std::string src = R"({
        "arr": ["0", "1", "2", "3", "4", "5", "6","7","8", "9", "10", "11"]
    })";
  
    try
    {
        auto result = jsoncons::json::parse(src);
        std::cout << PrettyPrint(result) << std::endl;
        std::cout << std::endl;

        auto flatResult = jsoncons::jsonpointer::flatten_with_padded_array_indexes(result);
        std::cout << PrettyPrint(flatResult) << std::endl;
        std::cout << std::endl;

        auto unflatten = jsoncons::jsonpointer::unflatten(flatResult);
        std::cout << PrettyPrint(unflatten) << std::endl;
    }
    catch (const std::exception& e)
    {
        std::cout << "Failed: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}
```

**What compiler, architecture, and operating system?**

Visual Studio 2022 on Windows 11,
Toolset: Visual Studio 2022 (v143),
C++ Language Standard: Preview - ISO C++23 Standard (/std:c++23preview)

**What jsoncons library version?**

Latest release: 1.4.3

**Additional notes**

One issue was found in the `try_unflatten_array` implementation  which was trying to match sequential values when it enumerates and parses the indexes - the next it finds after 1 is 10, not 2 .
```
...
​                auto s = *it;
                std::size_t n{0};
                auto r = jsoncons::utility::dec_to_integer(s.data(), s.size(), n);
                if (r.ec == std::errc() && (index++ == n))
                {
                    if (!part->is_array())
                    {
                        *part = Json(json_array_arg);
                    }
,,,
```
This implementation can be easily modified to check that, after enumerating all items, the maximum index value is equal to the number of parsed indexes minus 1.  This will ensure that the array type is preserved but the original order of the elements in the array will not be preserved,

One possible way to preserve the array element order could be to provide an option for the flatten operation to pad the indexes with leading zeroes so that their original relative order is preserved. I played a bit with this idea and it worked nicely:

Added extra parameter `bool with_padded_array_indexes` to `flatten_` and modified the implementation to pad indexes with leading zeroes when the parameter is set to `true`
```
...
    size_t decimal_positions(size_t value)
    {
      size_t pos = 0u;
      while (value > 0)
      {
        ++pos;
        value /= 10;
      }

      return pos;
    }

    template <typename Json>
    void flatten_(const std::basic_string<typename Json::char_type>& parent_key,
                  const Json& parent_value,
                  Json& result,
                  bool with_padded_array_indexes)
    {
        using char_type = typename Json::char_type;
        using string_type = std::basic_string<char_type>;

        switch (parent_value.type())
        {
            case json_type::array_value:
            {
                if (parent_value.empty())
                {
                    // Flatten empty array to null
                    //result.try_emplace(parent_key, null_type{});
                    //result[parent_key] = parent_value;
                    result.try_emplace(parent_key, parent_value);
                }
                else
                {
                    auto max_size = parent_value.size();
                    string_type padding_zeroes(with_padded_array_indexes ? decimal_positions(max_size) : 0, 0x30);
                    for (std::size_t i = 0; i < max_size; ++i)
                    {
                        if ( 0 == i % 10 && !padding_zeroes.empty())
                        {
                            padding_zeroes.resize(padding_zeroes.size()-1);
                        }
                        
                        string_type key(parent_key);
                        key.push_back('/');
                        if (!padding_zeroes.empty())
                        {
                          key += padding_zeroes;
                        }
                        jsoncons::utility::from_integer(i,key);
                        flatten_( key, parent_value.at(i), result, with_padded_array_indexes);
                    }
                }
                break;
            }
...
```

and then added a new method

```
​    template <typename Json> Json flatten_with_zero_padded_array_indexes(const Json &value) {
      Json result;
      std::basic_string<typename Json::char_type> parent_key;
      flatten_(parent_key, value, result, true);
      return result;
    }
```

The original method calls with flatten_ with the bool parameter set to `false`
```
​    template <typename Json>
    Json flatten(const Json& value)
    {
        Json result;
        std::basic_string<typename Json::char_type> parent_key;
        flatten_(parent_key, value, result, false);
        return result;
    }
```

**Comment by danielaparker** [comment]
You can preserve order by using `jsoncons::ojson`, 

```cpp
#include <jsoncons/json.hpp>
#include <jsoncons_ext/jsonpointer/jsonpointer.hpp>
#include <jsoncons_ext/jsonpointer/jsonpointer_error.hpp>

#include <iostream>
#include <string>

inline std::string PrettyPrint(const jsoncons::ojson & data) {
    std::string s;
    data.dump_pretty(s, jsoncons::json_options{}.indent_size(2).spaces_around_comma(
        jsoncons::spaces_option::no_spaces));
    return s;
}

int main()
{

    std::string src = R"({
        "arr": ["0", "1", "2", "3", "4", "5", "6","7","8", "9", "10", "11"]
    })";

    try
    {
        auto result = jsoncons::ojson::parse(src);
        std::cout << PrettyPrint(result) << std::endl;
        std::cout << std::endl;

        auto flatResult = jsoncons::jsonpointer::flatten(result);
        std::cout << PrettyPrint(flatResult) << std::endl;
        std::cout << std::endl;

        auto unflatten = jsoncons::jsonpointer::unflatten(flatResult);
        std::cout << PrettyPrint(unflatten) << std::endl;
    }
    catch (const std::exception& e)
    {
        std::cout << "Failed: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}
```
Output:

```
{
  "arr": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11"
  ]
}

{
  "/arr/0": "0",
  "/arr/1": "1",
  "/arr/2": "2",
  "/arr/3": "3",
  "/arr/4": "4",
  "/arr/5": "5",
  "/arr/6": "6",
  "/arr/7": "7",
  "/arr/8": "8",
  "/arr/9": "9",
  "/arr/10": "10",
  "/arr/11": "11"
}

{
  "arr": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11"
  ]
}
```

**Comment by danielaparker** [comment]
But I agree that the recovered array should be the same as the original for `jsoncons::json` too.

**Comment by danielaparker** [comment]
This (and a couple of other issues with unflatten) should be fixed on master.

**Comment by NiN9876** [comment]
Thank you for resolving the issue so quickly.

Could you please check for a possible regression? This test fails in my environment since the `unflattened` value is `null`, not an empty object.

```
   TEST(JconsTests, FlattenAndUnflatten_Preserve_DefaultValue)
    {
        jsoncons::json original;
        auto flattened = jsoncons::jsonpointer::flatten(original);
        auto unflattened = jsoncons::jsonpointer::unflatten(flattened);
        EXPECT_EQ(original, unflattened);
    }
```

**Comment by danielaparker** [comment]
This should be fixed on master, I've included your test case.

**Comment by NiN9876** [comment]
The flatten/unflatten test is now passing but the trace shows somewhat strange flattened result:
```
Test: DefaultValue
Original: {}
Flattened: {
  "": {}
}
Unflattened: {}
```

Same results are produced for values with primitive types and for empty array causing the flatten/unflatten test to fail:
```
===================
Test: IntegerValue
Original: 123
Flattened: {
  "": 123
}
Unflattened: {}
===================

===================
Test: EmptyArray
Original: []
Flattened: {
  "": []
}
Unflattened: {}
===================
```  


Not sure what is the best case to handle all these special cases. Perhaps throwing an exception when the parameter is a value with primitive type, and returning it directly back when it is an empty object or an empty array?

`unflatten` already throws when called with primitive types. May need to be tweaked to return back empty object and empty array values. Currently the result from calling it with empty object is an empty array which seems wrong.
```
Test: DefaultValue
Original: {}
test_unflattened: []
```

**Comment by danielaparker** [comment]
Could you check these cases once more with the latest code on master? Thanks!

**Comment by NiN9876** [comment]
Thank you!
`flatten`/`unflatten` tests now look good for all types and special cases.

There is only one minor issue remaining when calling `unflatten` with an empty object - it returns an empty array. 
```
Original: {}
Result: []
```
Returning an empty object or just throwing an exception could be better options.

**Comment by danielaparker** [comment]
I think an empty object argument to `unflatten` should have the same behavior as a non-object - both should throw. Fixed on master.

**Comment by NiN9876** [comment]
Unfortunately our tests picked up another regression which was traced to `unflatten` returning empty object from the following content
```
 {
  "": {},
  "/r1": "v1",
  "/r2": "v2"
}
```

I distilled the use case in a separate test which illustrates what was happening:  
a json object is flattened, an empty json object is flattened, the flattened contents are merged and then the merged result is unflattened. 

Tthis is the test execution trace:

```
original: {
  "r1": "v1",
  "r2": "v2"
}
empty: {}
Flattened original: {
  "/r1": "v1",
  "/r2": "v2"
}
Flattened empty: {
  "": {}
}
Flattened merged: {
  "": {},
  "/r1": "v1",
  "/r2": "v2"
}
Unflattened merged: {}
error: Expected equality of these values:
  original
    Which is: {"r1":"v1","r2":"v2"}
  unflattened
    Which is: {}
```

**Comment by NiN9876** [comment]
Apparently the issue was tagged as resoved shortly before I submitted my last comment.
Should I put it in a separate issue against master?

**Comment by danielaparker** [comment]
Easier just to remove the resolved tag :-) Will have a look.

Incidentally, you're welcome to submit a PR to add any tests for behavior that you depend on to https://github.com/danielaparker/jsoncons/blob/master/test/jsonpointer/src/jsonpointer_flatten_tests.cpp, or send them to me in GTest format, and I'll add them.

**Comment by danielaparker** [comment]
~~Did I miss something?~~

Sorry, misread your example.

**Comment by danielaparker** [comment]
My question is, what original document when flattened would produce this JSON?

```json
{
  "": {},
  "/r1": "v1",
  "/r2": "v2"
}
```
I don't think there is one, I don't think that's a valid flattened JSON.

**Comment by danielaparker** [comment]
I experimented with changing the code such that the `"": {}` member gets skipped rather than resulting in a returned empty object, and that results in the unflattened output  

```json
{"r1":"v1","r2":"v2"}
```

which I think is what you want, but I don't understand the motivation behind constructing the flattened value, which I don't think would be produced by a flatten operation on any original JSON.

I compared with nlohmann, changing the flattened representation to

```json
{
  "": null,
  "/r1": "v1",
  "/r2": "v2"
}
```

(nlohmann doesn't allow empty objects as values in flattened representations)

which produced
```json
 {"r1":"v1","r2":"v2"}
```

So I guess nlohmann does something similar.

**Comment by NiN9876** [comment]
Sorry, should have provided the test instead of the trace log script. The value passed to `unflatten` was produced by merging two flattened values:

```
    TEST(JsonconsTests, Flatten_FlattenEmptyObject_MergeOrUpdate_Unflatten)
    {
        auto empty = jsoncons::json::parse(R"({})");
        std::cout << "empty: " << jsoncons::pretty_print(empty) << std::endl;

        auto original = jsoncons::json::parse(R"({
                            "r1": "v1",
                            "r2": "v2"
                        })");
        std::cout << "original: " << jsoncons::pretty_print(original) << std::endl;

        auto flattenedOriginal = jsoncons::jsonpointer::flatten(original);
        std::cout << "Flattened original: " << jsoncons::pretty_print(flattenedOriginal) << std::endl;

        auto flattenedEmpty = jsoncons::jsonpointer::flatten(empty);
        std::cout << "Flattened empty: " << jsoncons::pretty_print(flattenedEmpty) << std::endl;

        flattenedEmpty.merge_or_update(flattenedOriginal);
        std::cout << "Flattened merged: " << jsoncons::pretty_print(flattenedEmpty) << std::endl;

        auto unflattened = jsoncons::jsonpointer::unflatten(flattenedEmpty);
        std::cout << "Unflattened merged: " << jsoncons::pretty_print(unflattened) << std::endl;

        EXPECT_EQ(original, unflattened);
    }
```

**Comment by danielaparker** [comment]
But by merging the two flattened values, don't you end up with a new value that cannot be reproduced by applying a flatten operation to any single JSON value? And if so, what is the meaning of that new value? If it's to be considered "flattened", what is it flattened of? Why would unflatten be expected to work on a value that wasn't produced by flatten, and cannot be produced by flatten?

We can give you the behavior that you're looking for, but I'm still struggling to understand the motivation.

**Comment by NiN9876** [comment]
The presented test case was created as an illustration of what was happening in existing code which performs some data processing and produces several "data segments" - flattened json objects. These segments are subsequently merged and the merge result unflattened. 

Some of the segments may not contain data, hence the presence of flattened empty object.

The latest shipped version 1.4.3 can handle such cases. When this Json is passed to `unflatten`
```
​{
  "": {},
  "/a": 1,
  "/b": 2
}
```
 the result is 
```
​{
  "a": 1,
  "b": 2
}
```

**Comment by danielaparker** [comment]
This should be addressed on master, please confirm.

**Comment by NiN9876** [comment]
Confirmed,
It all works now. Thank you!

Nit:
Since `unflatten` throwing an exception on empty object is a change of behviour compared to 1.4.3
* it deserves a line in the next relese notes
* the error message text can be updated to "Argument to unflatten must be a non-empty object"`
https://github.com/danielaparker/jsoncons/blob/c9f5c3d529112d962a3ccc19780996f45be0b114/include/jsoncons_ext/jsonpointer/jsonpointer_error.hpp#L93

**Comment by danielaparker** [comment]
I've made those changes, thanks.
